name: GommeMode
version: 2.0
author: AronikTV
main: de.AronikTV.gommemode.GommeMode

commands:
  gommemode:
    aliases: [gm]
    description: Der gommemode-command.
    usage: /<command> <arguments>
