name: PixelMode
version: 1.0
author: AronikTV
main: de.puriyaspielt.gommemode.GommeMode

commands:
  gommemode:
    aliases: [gm]
    description: The pixelmode-command.
    usage: /<command> <arguments>